# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sSMuL48q388OxbnpLGiH-lLz3kyGOh1
"""

!pip install streamlit

import streamlit as st

st.set_page_config(page_title="Mi propuesta 💌", layout="centered")
st.title("💌 Una propuesta muy especial 💌")

# Diapositivas
slides = [
    "💌 Una propuesta muy importante 💌\n(pero con amor)",
    "Hola,\nesto no es cualquier presentación...\nla hice pensando en ti 🤍",
    "Razones por las que me gustas:\n• Me haces reír\n• Me gusta estar contigo\n• Contigo todo se siente más bonito\n• Simplemente eres tú",
    "Pruebas irrefutables:\n📸 Evidencia #1\n📸 Evidencia #2\n📸 Evidencia #3",
    "Mi propuesta oficial:\n• Salidas lindas\n• Risas aseguradas\n• Abrazos ilimitados\n• Momentos que valgan la pena",
    "Beneficios de aceptar:\n✔ Buena compañía\n✔ Fotos bonitas\n✔ Nuevos recuerdos\n✔ Alguien que te elige",
    "💘 ¿Quieres ser mi Valentín? 💘\nNo hay respuesta incorrecta...\n(bueno, sí la hay 😌)",
    "Gracias por llegar hasta aquí 💖"
]

# Slider para navegar entre diapositivas
slide_number = st.slider("Diapositiva", 1, len(slides), 1)
st.markdown(f"### {slides[slide_number - 1]}")