# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sSMuL48q388OxbnpLGiH-lLz3kyGOh1
"""

!pip install streamlit

import streamlit as st

# Configuración de la página
st.set_page_config(page_title="Mi propuesta 💌", layout="centered")

st.title("💌 Una propuesta muy especial 💌")

# Lista de diapositivas (solo texto)
slides = [
    {"text": "💌 Una propuesta muy importante 💌\n(pero con amor)"},
    {"text": "Hola,\nesto no es cualquier presentación...\nla hice pensando en ti 🤍"},
    {"text": "Razones por las que me gustas:\n\n• Me haces reír\n• Me gusta estar contigo\n• Contigo todo se siente más bonito\n• Simplemente eres tú"},
    {"text": "Pruebas irrefutables:\n\n📸 Evidencia #1\n📸 Evidencia #2\n📸 Evidencia #3"},
    {"text": "Mi propuesta oficial:\n\n• Salidas lindas\n• Risas aseguradas\n• Abrazos ilimitados\n• Momentos que valgan la pena"},
    {"text": "Beneficios de aceptar:\n\n✔ Buena compañía\n✔ Fotos bonitas\n✔ Nuevos recuerdos\n✔ Alguien que te elige"},
    {"text": "💘 ¿Quieres ser mi Valentín? 💘\nNo hay respuesta incorrecta...\n(bueno, sí la hay 😌)"},
    {"text": "Gracias por llegar hasta aquí 💖"}
]

# Selector de diapositiva
slide_number = st.slider("Diapositiva", 1, len(slides), 1)
slide = slides[slide_number - 1]

# Mostrar el texto de la diapositiva
st.markdown(f"### {slide['text']}")